[package]
name = "cellar_rebalancer"
authors = []
version = "0.1.0"
edition = "2018"

[dependencies]
gumdrop = "0.7"
serde = { version = "1", features = ["serde_derive"] }
thiserror = "1"
ethers = {git = "https://github.com/gakonst/ethers-rs", features=["abigen"]}
abscissa_tokio = "0.6.0-pre.1"
serde_json = "1.0.64"
tower = { version = "0.4", features = ["buffer", "util"] }
tokio ={version ="1", features = ["macros"]}
futures = "0.3"
chrono = "0.4"
iqhttp = { version = "0.1", features = ["json"] }
mongodb = "2.0.0-beta.2"
bson = {version = "2.0.0-beta.2", features = ["chrono-0_4"]}
uniswap_v3_sdk ={git ="https://github.com/PeggyJV/uniswap_sdk_rs",branch = "main"}
num-bigint = "0.4"
num-traits = "0.2"
toml = { version = "0.5" }


bip32 = "0.2"
k256 = { version = "0.9", features = ["pem"] }
pkcs8 = { version = "0.7", features = ["pem"] }
signatory = "0.23.0-pre"
rand_core = { version = "0.6", features = ["std"] }
rpassword = "5"

[dependencies.abscissa_core]
version = "0.6.0-pre.1"
# optional: use `gimli` to capture backtraces
# see https://github.com/rust-lang/backtrace-rs/issues/189
# features = ["gimli-backtrace"]


[dev-dependencies]
abscissa_core = { version = "0.6.0-pre.1", features = ["testing"] }
once_cell = "1.2"

