[package]
name = "cellar_rebalancer_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
default-members = [
	"cellar_rebalancer",
	"cellar_rebalancer_abi",
	"steward_abi_build",
	"steward_proto",
	"steward_proto_build",
]
members = [
	"cellar_rebalancer",
	"cellar_rebalancer_abi",
	"steward_abi_build",
	"steward_proto",
	"steward_proto_build",
]
[dependencies]
cellar_rebalancer = { path = "./cellar_rebalancer" }
cellar_rebalancer_abi = { path = "./cellar_rebalancer_abi" }
steward_abi_build = { path = "./steward_abi_build" }
steward_proto = { path = "./steward_proto" }
steward_proto_build = { path = "./steward_proto_build" }
