[package]
name = "contract_monitor"
authors = []
version = "0.1.0"
edition = "2018"

[dependencies]
gumdrop = "0.7"
serde = { version = "1", features = ["serde_derive"] }
thiserror = "1"
ethers = {version = "0.2", features=["abigen"]}
abscissa_tokio = "0.6.0-pre.1"
serde_json = "1.0.64"
tower = { version = "0.4", features = ["buffer", "util"] }
tokio ={version ="1", features = ["macros"]}
futures = "0.3"
chrono = "0.4"
iqhttp = { version = "0.1", features = ["json"] }


[dependencies.abscissa_core]
version = "0.6.0-pre.1"
# optional: use `gimli` to capture backtraces
# see https://github.com/rust-lang/backtrace-rs/issues/189
# features = ["gimli-backtrace"]

[dev-dependencies]
abscissa_core = { version = "0.6.0-pre.1", features = ["testing"] }
once_cell = "1.2"

