[package]
name = "sommelier_steward"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
default-members = [
	"steward",
	"steward_abi",
	"steward_abi_build",
	"steward_proto",
	"steward_proto_build",
]
members = [
	"steward",
	"steward_abi",
	"steward_abi_build",
	"steward_proto",
	"steward_proto_build",
]
[dependencies]
steward = { path = "./steward" }
steward_abi = { path = "./steward_abi" }
steward_abi_build = { path = "./steward_abi_build" }
steward_proto = { path = "./steward_proto" }
steward_proto_build = { path = "./steward_proto_build" }
