[package]
name = "cellar_rebalancer_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
default-members = ["abi_build", "cellar_rebalancer", "rebalancer_abi"]
members = [
	"abi_build",
	"cellar_rebalancer",
    "rebalancer_abi",
]
[dependencies]
abi_build = {path = "./abi_build"}
cellar_rebalancer = {path = "./cellar_rebalancer"}
rebalancer_abi = {path = "./rebalancer_abi"}