keystore = "/tmp/keystore"

[gravity]
contract = "0x0000000000000000000000000000000000000000"
fees_denom = "stake"

[ethereum]
key_derivation_path = "m/44'/60'/0'/0/0"
rpc = "https://eth-mainnet.alchemyapi.io/v2/AgvTVg4Y5rSU5T7bYtMRqAbiFMcaNsMw"

[cosmos]
key_derivation_path = "m/44'/118'/0'/0/0"
grpc = "http://localhost:9090"
prefix = "cosmos"

[cosmos.gas_price]
amount = 0.001
denom = "stake"

[metrics]
listen_addr = "127.0.0.1:3000"

[[cellars]]
pair_id = "0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8"
cellar_address = "0x08c0a0B8D2eDB1d040d4f2C00A1d2f9d9b9F2677"
pool_address = "0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8"
weight_factor = 100
max_gas_price_gwei = 100
pair_database = "USDC_ETH_0pt3"

[cellars.token_0]
decimals = 6
symbol = "USDC"
address = "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"

[cellars.token_1]
decimals = 18
symbol = "ETH"
address = "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"

[cellars.duration]
secs = 86400
nanos = 0

[keys]
keystore = "/home/ugochi/keys"
rebalancer_key = "cellar"

[mongo]
host = "mongodb://localhost:27017/?directconnection=true"