name: Rust tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Set up Rust caches
        uses: actions/cache@v2
        id: rust-cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
      - name: Run steward acceptance tests
        run: cargo test --all --verbose

  rust-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Set up Rust caches
        uses: actions/cache@v2
        id: rust-cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
      - name: Run Cargo build
        run: cargo build

  fmt:
    name: Rustfmt
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Rust format
        run: rustup component add rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Run clippy
        run: rustup component add clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -p steward -- -D warnings --no-deps
